language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
env:
  - DB=sqlite
# command to run tests
script: nosetests --with-coverage --with-coverage --cover-erase --cover-html

after_success:
  - coveralls